spring:
  cloud:
    gateway:
      routes:
        - id: Auth-route
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}

  application:
    name: API-GATEWAY
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/